# Generated by Django 5.1.4 on 2025-01-23 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customerprofile_alternate_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=100)),
                ('experience_years', models.IntegerField(default=0)),
                ('qualifications', models.TextField()),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_days', models.JSONField(default=list)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctor_profiles/')),
                ('about_me', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to='authentication.customerprofile')),
            ],
        ),
    ]
