# Generated by Django 5.1.4 on 2025-02-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_doctor_available_days_availability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
