# Generated by Django 5.1.4 on 2025-02-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_doctor_consultation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_duration',
            field=models.IntegerField(default=15),
        ),
    ]
