# Generated by Django 5.1.4 on 2025-02-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_doctor_consultation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation_duration',
            field=models.IntegerField(choices=[(5, '5 min'), (10, '10 min'), (15, '15 min'), (20, '20 min'), (30, '30 min')], default=15),
        ),
    ]
