# Generated by Django 5.1.4 on 2025-02-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_doctor_consultation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='pin',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
