# Generated by Django 5.1.4 on 2025-01-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_Store', '0003_orderaddress_order_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderaddress',
            old_name='address_line_1',
            new_name='address_line',
        ),
        migrations.RemoveField(
            model_name='orderaddress',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='alternate_phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='orderaddress',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
