# Generated by Django 5.1.4 on 2025-01-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_Store', '0006_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
