# Generated by Django 5.1.4 on 2025-02-21 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_booking'),
        ('authentication', '0008_alter_doctor_consultation_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='authentication.customerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('doctor', 'date', 'start_time')},
        ),
    ]
