# Generated by Django 5.1.4 on 2025-02-26 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_appointment_diagnosis'),
        ('e_Store', '0008_remove_product_is_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='prescription',
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dosage', models.CharField(blank=True, max_length=255, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='appointment.appointment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescribed', to='e_Store.product')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='prescribed_medicines',
            field=models.ManyToManyField(related_name='prescriptions', through='appointment.Prescription', to='e_Store.product'),
        ),
    ]
