# Generated by Django 5.1.4 on 2025-02-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_remove_appointment_prescription_prescription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='custom_medicine_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
