# Generated by Django 5.1.4 on 2025-03-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0009_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
