# Generated by Django 5.1.4 on 2025-03-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0011_alter_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='chat_videos'),
        ),
    ]
