# Generated by Django 5.1.4 on 2025-02-21 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_doctor_consultation_duration'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('doctor', 'day', 'start_time', 'end_time')},
        ),
    ]
